// <auto-generated />
using System;
using AztecTariff.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AztecTariff.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240202121906_summarizedcats")]
    partial class summarizedcats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("AztecTariff.Models.PDFData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeABV")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalesAreaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TempFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PDFData");
                });

            modelBuilder.Entity("AztecTariff.Models.PDFProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludedInPdf")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PDFDataId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Pricing")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PDFProducts");
                });

            modelBuilder.Entity("AztecTariff.Models.Pricing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstateId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalesAreaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pricing");
                });

            modelBuilder.Entity("AztecTariff.Models.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ABV")
                        .HasColumnType("REAL");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstateId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Included")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Portion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProdName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductTariffName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TariffCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AztecTariff.Models.SalesArea", b =>
                {
                    b.Property<int>("SalesAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FooterMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Included")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginalSalesAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SAName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TariffName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isEvent")
                        .HasColumnType("INTEGER");

                    b.HasKey("SalesAreaId");

                    b.ToTable("SalesAreas");
                });

            modelBuilder.Entity("AztecTariff.Models.SummarizedCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalesAreaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SummarizedCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
